// CREATE KEYSPACE hotel WITH replication = {‘class’: ‘SimpleStrategy’, ‘replication_factor’ : 3};

// CREATE TYPE hotel.address (
//   id number,
//   gameId: number,
//   title: String,
//   publisher: String,
//   reviewScore: Number,
//   reviewCount: Number,
//   ageRating: String,
//   newPrice: Number,
//   usedPrice: Number,
//   digitalPrice: Number,
//   storeLocation: String,
//   inStock: Boolean,
// );